README.md

Turn `My favourite vehicle is: '%v'!` into `My favourite vehicle is: 'Landstalker'!`

Display actual vehicle name instead of character - readme test code

---

runtime/download.go
runtime/ensure.go
runtime/resource.go

Checksum now checks against the downloaded server archive

---

rook/load.go
util/util.go

Fix two typos

---

compiler/download.go
rook/build_test.go
types/compiler.go

bumped the default compiler version to 3.10.9

---

download/compiler_cache.go

Fixed returning when updating compiler list

---

rook/ensure.go
runtime/ensure_plugins.go
types/resource.go

Adds versioning support for the issue.
fix #311

Added versioning for remote packages

---

compiler/compiler.go

Fixed crash when output folder didn't exist

---

compiler/compiler.go
compiler/download.go
rook/build.go
types/compiler.go

Adds the ability to use a custom repository for downloading custom versions of the compiler.

Added custom compiler repos

---

runtime/ensure.go
runtime/resource.go
runtime/run.go

Added support for runtime binaries paths

---

commands/server_download.go
commands/server_ensure.go
commands/server_init.go
commands/server_run.go

deprecate server subcommands

---

go.mod
go.sum
rook/ensure.go

Delete package folder after failed ensure

---

rook/initialise.go

Added package type options to config init

---

rook/cache.go

Fixed installing failed dependencies

---

.github/workflows/test.yml

Now runs the full tests instead of skipping them.

Run full tests for actions

---

.github/workflows/release.yml
.goreleaser.yml

* Updated goreleaser config
* Added release workflow
* fixed missed tests keyword

Fix workflow (#386)

---

runtime/ensure_plugins.go

Fixed resources not being pulled if no version was specified

---

.github/workflows/release.yml
runtime/ensure_plugins.go

This is a staging PR to prepare for v1.9.1
Note: When merging this, use `create merge commit` not `squash and merge`.

Staging v1.9.1 

---

go.mod
go.sum
pawnpackage/package.go
run/runtime.go

Fixes runtime structs being written to yaml by upgrading to v3

---

pkgcontext/build.go

Adds the main package to the list of include paths

---

build/compiler.go
compiler/compiler.go
pkgcontext/build.go

Added the ability to run pre/post build commands

---

pkgcontext/install.go

Adds a tag if one is not present when installing a new dependency

---

go.mod
go.sum
runtime/run_posix.go

Logs:
```
cheaterman@cmans-laptop ~/Dev/open.mp/pawn-test-scripts $ sampctl package run
failed to run package: received runtime error: failed to start server: failed to start pty: fork/exec /home/cheaterman/Dev/open.mp/pawn-test-scripts/samp03svr: Setctty set but Ctty not valid in child
```

Fix pty issues on Linux, see https://github.com/creack/pty/issues/96

---

README.md

Fix the version
